defaults: &defaults
  search_scopes:
    local:
      enabled: true
    cdi:
      enabled: true

  campus_networks:
    - "127.0.0.1"
    - "10.0.2.0/24"
    - "131.234.0.0/1"

  cover_images:
    enabled: true
    access_token: "ae9dcc0d-bc22-48ca-a343-e840429fd043"

  closed_stack_orders:
    url: "http://ubstage18.uni-paderborn.de:81/cgi-mag/magbest_via_katalog"

  shelf_finder:
    enabled: true
    base_url: "https://regaldb.ub.uni-paderborn.de"

  link_resolver:
    #base_url: "https://hbz-pad.userservices.exlibrisgroup.com/view/uresolver/49HBZ_PAD/openurl"
    base_url: "https://eu03.alma.exlibrisgroup.com/view/uresolver/49HBZ_PAD/openurl"

  piwik_tracking:
    enabled: true
    piwik_domain: "piwik.uni-paderborn.de"
    piwik_site_id: "141"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
